name = "cool-english-cosmos"
compatibility_date = "2026-08-09"

[env.production]
name = "cool-english-cosmos-prod"

[build]
command = "pnpm build"
cwd = "./"

[assets]
directory = "dist/public"
binding = "ASSETS"
